name: CICD

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-test-env:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: "test"

  deploy-stage-env:
    needs: [deploy-test-env]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: "stage"

  deploy-prod-env:
    needs: [deploy-stage-env]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: "prod"
