name: CICD

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-test:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: "test"

  deploy-stage:
    needs: [deploy-test]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: "stage"

  deploy-prod:
    needs: [deploy-stage]
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment-to-deploy: "prod"
