name: Deploy Staging

on:
  workflow_run:
    workflows: ["Deploy Test"]
    types:
      - completed
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  ENVIRONMENT: stage

jobs:
  build:
    environment: "stage"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: echo "Placeholder - steps to complete STAGE BUILD would go here..."
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: echo "Placeholder - steps to complete STAGE DEPLOYMENT would go here..."
