name: Deploy Prod

on:
  workflow_run:
    workflows: ["Deploy Staging"]
    types:
      - completed

env:
  ENVIRONMENT: prod

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: "prod"
    steps:
      - run: echo "Placeholder - steps to complete PROD BUILD would go here..."
      - run: echo ${{ github.ref }}

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [build]
    steps:
      - run: echo "Placeholder - steps to complete PROD DEPLOYMENT would go here..."
