name: Deploy Staging

on:
  workflow_run:
    workflows: ["Deploy Test"]
    types:
      - completed

env:
  ENVIRONMENT: stage

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: "stage"
    steps:
      - run: echo "Placeholder - steps to complete STAGE BUILD would go here..."

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [build]
    steps:
      - run: echo "Placeholder - steps to complete STAGE DEPLOYMENT would go here..."
