name: Deploy Environment

on:
  workflow_call:
    inputs:
      environment-to-deploy:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: ${{ inputs.environment-to-deploy }}
    steps:
      - run: echo "Placeholder - steps to complete ${{ inputs.environment-to-deploy }} BUILD would go here..."

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: ${{ inputs.environment-to-deploy }}
    needs: [build]
    steps:
      - run: echo "Placeholder - steps to complete ${{ inputs.environment-to-deploy }} DEPLOYMENT would go here..."

  integration-test:
    if: inputs.environment-to-deploy != 'prod'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [deploy]
    steps:
      - run: echo "Non-production environment detected, this step will run"
