name: Deploy Development

on: pull_request

env:
  ENVIRONMENT: dev

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: "dev"
    steps:
      - run: echo "Placeholder - steps to complete DEV BUILD would go here..."

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [build]
    steps:
      - run: echo "Placeholder - steps to complete DEV DEPLOYMENT would go here..."