name: Deploy Test

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  ENVIRONMENT: test

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: "test"
    steps:
      - run: echo "Placeholder - steps to complete TEST BUILD would go here..."

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [build]
    steps:
      - run: echo "Placeholder - steps to complete TEST DEPLOYMENT would go here..."
      - run: exit 1 # temp to test guard