name: Deploy Development

on: pull_request

env:
  ENVIRONMENT: dev

jobs:
  build:
    environment: "dev"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: echo "Placeholder - steps to complete DEV BUILD would go here..."
      - run: echo ${{ github.ref }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: echo "Placeholder - steps to complete DEV DEPLOYMENT would go here..."