name: Deploy Test

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  ENVIRONMENT: test

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: echo "Placeholder - steps to complete TEST deployment would go here..."
