name: Deploy Staging

on:
  workflow_run:
    workflows: ["Deploy Test"]
    types:
      - completed

env:
  ENVIRONMENT: stage

jobs:
  build:
    environment: "stage"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: echo "Placeholder - steps to complete STAGE BUILD would go here..."
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.ref_name }}
      - run: echo ${{ github.ref_type }}
      - run: echo ${{ github.sha }}
      - run: echo ${{ github.event }}
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.base_ref }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - run: echo "Placeholder - steps to complete STAGE DEPLOYMENT would go here..."
