name: Deploy Staging

on:
  workflow_run:
    workflows: ["Deploy Test"]
    types:
      - completed

env:
  ENVIRONMENT: stage

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    environment: "stage"
    steps:
      - run: echo "Placeholder - steps to complete STAGE BUILD would go here..."
      - run: echo ${{ github.ref }}      # refs/heads/main
      - run: echo ${{ github.ref_name }} # main
      - run: echo ${{ github.ref_type }} # branch
      - run: echo ${{ github.sha }}      # 5df564d69cc9792088370af042e6ec104c81dacc
      - run: echo ${{ github.event }}    # Object (need to json decode)
      - run: echo ${{ github.head_ref }} # <empty>
      - run: echo ${{ github.base_ref }} # <empty>

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: [build]
    steps:
      - run: echo "Placeholder - steps to complete STAGE DEPLOYMENT would go here..."
